name: "Version Cleaner Action"
description: "A GitHub Action for deleting packages with specific version from a GitHub repository"
inputs:
  github-repository:
    description: "The GitHub repository where snapshots will be deleted"
    required: false
    default: ${{ github.repository }}
  package-type:
    description: "The package type to delete (e.g., maven)"
    required: true
  version-tag:
    description: "The tag to use to identify version packages"
    required: false
    default: "SNAPSHOT"
  is-version-tag-strict:
    description: "Whether to use strict matching for version tag"
    required: false
    default: "true"
  github-token:
    description: "The GitHub token to use for deleting packages. See required scopes in README.md"
    required: true
runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: Savrov/github-action-version-cleaner
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: action-version-cleaner
        path: .  # artifact will be saved in the current working directory
    - name: Run build with Gradle Wrapper
      shell: bash
      run: ./gradlew run
      env:
        GITHUB_REPOSITORY: ${{ inputs.github-repository }}
        PACKAGE_TYPE: ${{ inputs.package-type }}
        VERSION_TAG: ${{ inputs.version-tag }}
        IS_VERSION_TAG_STRICT: ${{ inputs.is-version-tag-strict }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
branding:
  icon: 'trash'
  color: 'green'