package model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class Repository(
    @SerialName("id") var id: Int? = null,
    @SerialName("node_id") var nodeId: String? = null,
    @SerialName("name") var name: String? = null,
    @SerialName("full_name") var fullName: String? = null,
    @SerialName("private") var private: Boolean? = null,
    @SerialName("owner") var owner: Owner? = Owner(),
    @SerialName("html_url") var htmlUrl: String? = null,
    @SerialName("description") var description: String? = null,
    @SerialName("fork") var fork: Boolean? = null,
    @SerialName("url") var url: String? = null,
    @SerialName("forks_url") var forksUrl: String? = null,
    @SerialName("keys_url") var keysUrl: String? = null,
    @SerialName("collaborators_url") var collaboratorsUrl: String? = null,
    @SerialName("teams_url") var teamsUrl: String? = null,
    @SerialName("hooks_url") var hooksUrl: String? = null,
    @SerialName("issue_events_url") var issueEventsUrl: String? = null,
    @SerialName("events_url") var eventsUrl: String? = null,
    @SerialName("assignees_url") var assigneesUrl: String? = null,
    @SerialName("branches_url") var branchesUrl: String? = null,
    @SerialName("tags_url") var tagsUrl: String? = null,
    @SerialName("blobs_url") var blobsUrl: String? = null,
    @SerialName("git_tags_url") var gitTagsUrl: String? = null,
    @SerialName("git_refs_url") var gitRefsUrl: String? = null,
    @SerialName("trees_url") var treesUrl: String? = null,
    @SerialName("statuses_url") var statusesUrl: String? = null,
    @SerialName("languages_url") var languagesUrl: String? = null,
    @SerialName("stargazers_url") var stargazersUrl: String? = null,
    @SerialName("contributors_url") var contributorsUrl: String? = null,
    @SerialName("subscribers_url") var subscribersUrl: String? = null,
    @SerialName("subscription_url") var subscriptionUrl: String? = null,
    @SerialName("commits_url") var commitsUrl: String? = null,
    @SerialName("git_commits_url") var gitCommitsUrl: String? = null,
    @SerialName("comments_url") var commentsUrl: String? = null,
    @SerialName("issue_comment_url") var issueCommentUrl: String? = null,
    @SerialName("contents_url") var contentsUrl: String? = null,
    @SerialName("compare_url") var compareUrl: String? = null,
    @SerialName("merges_url") var mergesUrl: String? = null,
    @SerialName("archive_url") var archiveUrl: String? = null,
    @SerialName("downloads_url") var downloadsUrl: String? = null,
    @SerialName("issues_url") var issuesUrl: String? = null,
    @SerialName("pulls_url") var pullsUrl: String? = null,
    @SerialName("milestones_url") var milestonesUrl: String? = null,
    @SerialName("notifications_url") var notificationsUrl: String? = null,
    @SerialName("labels_url") var labelsUrl: String? = null,
    @SerialName("releases_url") var releasesUrl: String? = null,
    @SerialName("deployments_url") var deploymentsUrl: String? = null
)
